# Generated by Django 5.2.8 on 2025-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musichistory',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='musichistory',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='musichistory',
            name='song_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musichistory',
            name='genre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='musichistory',
            name='mood',
            field=models.CharField(max_length=80),
        ),
    ]
