# Generated by Django 5.2.7 on 2025-11-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('sentiment', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=100)),
                ('music_file', models.FileField(blank=True, null=True, upload_to='music/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
