# Generated by Django 5.2.7 on 2025-11-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='spotify_artists',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='spotify_external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='spotify_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='spotify_track_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
