# Generated by Django 5.2.7 on 2025-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmusic',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generatedmusic',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generatedmusic',
            name='model_version',
            field=models.CharField(default='EnhancedMoodClassifier_v1', max_length=100),
        ),
    ]
